apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata: 
  name: external-secrets 
  namespace: {{ .Release.Namespace }}
spec: 
  refreshInterval: "1h" 
  secretStoreRef: 
    name: aws-secretsmanager
    kind: ClusterSecretStore 
  target: 
    name: {{ .Release.Name }}-secrets 
    creationPolicy: Owner 
  data: 
  # --- RDS (Oracle) 関連のシークレット --- 
  - secretKey: DB_HOST 
    remoteRef: 
      key: "rds_connection_details" 
      property: host 
  - secretKey: DB_PORT 
    remoteRef: 
      key: "rds_connection_details" 
      property: port 
  - secretKey: DB_NAME 
    remoteRef: 
      key: "rds_connection_details" 
      property: dbname 
  - secretKey: DB_USERNAME 
    remoteRef: 
      key: "rds_connection_details" 
      property: username 
  - secretKey: DB_PASSWORD 
    remoteRef: 
      key: "rds_connection_details" 
      property: password 
        
# --- Redis 関連のシークレット --- 
  - secretKey: REDIS_HOST
    remoteRef: 
      key: redis-token 
      property: host 
  - secretKey: REDIS_PORT 
    remoteRef: 
      key: redis-token 
      property: port 
  - secretKey: REDIS_USERNAME 
    remoteRef: 
      key: redis-token 
      property: username 
  - secretKey: REDIS_PASSWORD 
    remoteRef: 
      key: redis-token 
      property: password
  - secretKey: REDIS_SSL_ENABLED
    remoteRef: 
      key: redis-token 
      property: ssl

# --- Jwt 関連のシークレット --- 
  - secretKey: JWT_SECRET
    remoteRef: 
      key: jwt-secret 
      property: secret 
