apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata: 
  # Helmのリリース名を使って、一意なリソース名にする 
  name: external-secrets 
  # アプリケーションと同じ名前空間にデプロイ 
  namespace: {{ .Release.Namespace }}
spec: 
  # 1時間ごとに同期 
  refreshInterval: "1h" 
  # Terraformで作成したSecretStoreを参照 
  # ClusterSecretStoreを使う場合は kind: ClusterSecretStore に変更 
  secretStoreRef: 
    name: aws-secretsmanager
    kind: ClusterSecretStore 
  # ここで生成するKubernetes Secretの定義 
  target: 
    # Podから参照するSecretの名前 
    name: {{ .Release.Name }}-secrets 
    # Helmによるリソース管理を容易にするため、ownerReferenceを付与 
    creationPolicy: Owner 
        
  # どのデータを取得してくるかの定義 
  data: 
  # --- RDS (Oracle) 関連のシークレット --- 
  # AWSが自動生成したシークレットから各値を取得します。 
  - secretKey: DB_HOST 
    remoteRef: 
      key: "rds_connection_details" 
      property: host 
  - secretKey: DB_PORT 
    remoteRef: 
      key: "rds_connection_details" 
      property: port 
  - secretKey: DB_NAME 
    remoteRef: 
      key: "rds_connection_details" 
      property: dbname 
  - secretKey: DB_USERNAME 
    remoteRef: 
      key: "rds_connection_details" 
      property: username 
  - secretKey: DB_PASSWORD 
    remoteRef: 
      key: "rds_connection_details" 
      property: password 
        
# --- Redis 関連のシークレット --- 
# Terraformで作成した 'redis-auth-token' シークレットから各値を取得します。 
  - secretKey: REDIS_HOST
    remoteRef: 
      key: redis-token 
      property: host 
  - secretKey: REDIS_PORT 
    remoteRef: 
      key: redis-token 
      property: port 
  - secretKey: REDIS_USERNAME 
    remoteRef: 
      key: redis-token 
      property: username 
  - secretKey: REDIS_PASSWORD 
    remoteRef: 
      key: redis-token 
      property: password