apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: secretsmanager
spec:
  provider:
    aws:
      region: ap-northeast-1
      auth:
        jwt:
          serviceAccountRef:
            name: backend
            namespace: backend