services:
  oracle-db:
    image: gvenzl/oracle-free:23.3-slim-faststart
    container_name: oracle-db
    environment:
      - ORACLE_PASSWORD=${ORACLE_PASSWORD}
      - APP_USER=${APP_USER}
      - APP_USER_PASSWORD=${APP_USER_PASSWORD}
    ports:
      - "1521:1521"
    volumes:
      - ./db/init:/container-entrypoint-initdb.d

  backend:
    build: ./backend
    container_name: estimate-backend
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    ports:
      - "8080:8080"
    depends_on:
      - oracle-db

  frontend:
    build: ./frontend
    container_name: estimate-frontend
    ports:
      - "3000:80" # ホスト3000番でアクセス→コンテナnginxの80番
    depends_on:
      - backend