version: '3.9'

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@oracle-db:1521/FREEPDB1
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: oracle
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
    depends_on:
      - oracle-db

  oracle-db:
    image: container-registry.oracle.com/database/free
    container_name: oracle-db
    ports:
      - "1521:1521"
      - "5500:5500"  # EM Express用（任意）
    environment:
      ORACLE_PWD: oracle
    volumes:
      - ./db/init:/opt/oracle/scripts/startup