server:
    port: 8080
    error:
        whitelabel:
            enabled: false

spring:
    application:
        name: estimate-api
    datasource:
        url: jdbc:oracle:thin:@//${DB_HOST}:${DB_PORT}/${DB_NAME}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        driver-class-name: oracle.jdbc.OracleDriver
        hikari:
            connection-init-sql: ALTER SESSION SET CURRENT_SCHEMA=APP_OWNER
    data:
        redis:
            host: ${REDIS_HOST}
            port: ${REDIS_PORT}
            username: ${REDIS_USERNAME}
            password: ${REDIS_PASSWORD}
            ssl: 
                enabled: ${REDIS_SSL_ENABLED}