server:
    port: 8080
    error:
        whitelabel:
            enabled: false

spring:
    application:
        name: estimate-api
    datasource:
        url: ${SPRING_DATASOURCE_URL}
        username: ${SPRING_DATASOURCE_USERNAME}
        password: ${SPRING_DATASOURCE_PASSWORD}
        driver-class-name: oracle.jdbc.OracleDriver
    data:
        redis:
            host: redis
            port: 6379